/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import { Metadata } from 'next';
import {
  Check,
  Group,
  SectionHeading,
  SupportCard,
  Testimonials,
} from '~/components';
import { Figtree } from 'next/font/google';
import Link from 'next/link';
const figtree = Figtree({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Catchup Bookkeeping | Accountable',
  description: 'Generated by create next app',
};
export default function CatchupBKK() {
  return (
    <div
      className={[figtree.className, 'flex min-h-screen flex-col pt-24'].join(
        ' '
      )}
    >
      <Group key='home-hero'>
        <div className='pt-24 pb-[120px] max-w-[1230px] mx-auto'>
          <div className='grid grid-cols-2 w-full items-center'>
            <div className='flex flex-col'>
              <p className='text-midnight'>Catch Up Bookkeeping.</p>
              <h1 className='text-heading text-5xl leading-snug mt-2 max-w-[607px] font-bold'>
                Tidy up your financial records with Catch Up Bookkeeping.
              </h1>
              <p className='mt-4 max-w-[460px] text-body'>
                Don't let overdue bookkeeping stress you out. With Accountable,
                you can get your books up-to-date and ready for filing quickly
                with the help of our expert bookkeepers.
                <br />
                <br />
                For businesses that are two years or less behind on their
                bookkeeping
                <br />
              </p>

              <div className='mt-10 flex items-center gap-x-4'>
                <a
                  href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                  target='_blank'
                  className='bg-midnight text-white py-3 px-6 rounded-xl'
                >
                  Book a meeting
                </a>
                <a
                  href='#'
                  className='border border-midnight text-midnight py-3 px-6 rounded-xl'
                >
                  Watch a demo
                </a>
              </div>
            </div>
            <div>
              <img
                src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e8561f8ce14e3d5182150_image_services.png'
                loading='lazy'
                sizes='(max-width: 767px) 100vw, 673.5px'
                width='673.5'
                alt=''
                srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e8561f8ce14e3d5182150_image_services-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e8561f8ce14e3d5182150_image_services-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e8561f8ce14e3d5182150_image_services-p-1080.png 1080w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e8561f8ce14e3d5182150_image_services.png 1347w'
              />
            </div>
          </div>
        </div>
      </Group>

      <Group key='benefits'>
        <div className='mt-[120px] bg-[#fcfeff]'>
          <div className=' pb-[80px] max-w-[1230px] mx-auto flex flex-col items-center'>
            <SectionHeading
              title='BENEFITS'
              heading='Benefits of using Accountable for your bookkeeping'
              paragraph='Finance for businesses, powered by real humans. We work round the clock to assist you with anything you need.'
            />
            <div className='flex flex-col items-center justify-between max-w-[856px] w-full mt-[82px]'>
              <Group key='benefits grid'>
                <div className='flex items-center justify-between w-full'>
                  <div className='max-w-[248px] flex flex-col items-center gap-y-3 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6426f13db2096d417ae95205_fast.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className=' text-heading font-semibold'>
                      Swift Turnaround Times
                    </div>
                    <p className='text-body text-sm'>
                      Our efficient service quickly tackles overdue bookkeeping,
                      saving you time and reducing deadline stress.
                    </p>
                  </div>
                  <div className='max-w-[248px] flex flex-col items-center gap-y-3 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642510bd943fc89907d9e658_tax%202.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className=' text-heading font-semibold'>
                      Tidy tax-ready financials
                    </div>
                    <p className='text-body text-sm'>
                      We provide tax and audit-ready financials for every
                      catch-up year to simplify the process.
                    </p>
                  </div>
                  <div className='max-w-[248px] flex flex-col items-center gap-y-3 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6426f13d39d5afb7e9c0e444_stop.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className=' text-heading font-semibold'>
                      Erase misstatement Risk
                    </div>
                    <p className='text-body text-sm'>
                      Avoid misstated earnings; ensure accurate financial health
                      and prevent legal issues or tax overpayment
                    </p>
                  </div>
                </div>
              </Group>
              <Group key='cta'>
                <div className='mt-[72px] flex items-center gap-x-4'>
                  <a
                    href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                    target='_blank'
                    className='bg-midnight text-white py-3 px-6 rounded-xl'
                  >
                    Book a meeting
                  </a>
                  <a
                    href='#'
                    className='border border-midnight text-midnight py-3 px-6 rounded-xl'
                  >
                    Watch a demo
                  </a>
                </div>
              </Group>
            </div>
          </div>
        </div>
      </Group>
      <Group key='features'>
        <div className='mt-20 mb-[120px]'>
          <div className='flex flex-col items-center max-w-[1064px] w-full mx-auto'>
            <div className='flex flex-col text-center max-w-[620px] pb-20 '>
              <h3 className='text-heading text-[40px] font-bold leading-tight'>
                Features available to our catchup bookkeeping service{' '}
              </h3>
              <p className='text-xl text-body mt-[10px]'>
                Finance for businesses, powered by real humans. We work round
                the clock to assist you with anything you need.
              </p>
            </div>
            <Group key='check grid'>
              <Group key='first'>
                <div className='border-t border-[#f2f2f2] pt-20 flex items-start justify-between w-full'>
                  <div className='max-w-[364px] w-full flex flex-col'>
                    <h3 className='mt-4 text-heading font-bold text-[32px]'>
                      Regain control of your books effortlessly and without
                      stress.{' '}
                    </h3>
                    <p className='mt-2 text-body'>
                      With our experienced professionals and advanced automation
                      tools, you can manage your financial records efficiently
                      and without stress.
                    </p>
                  </div>
                  <div className='flex flex-col max-w-[530px] w-full gap-y-5'>
                    <Check
                      title='Efficient and error-free bookkeeping'
                      details="Whether you're missing months or years of bookkeeping or have no records at all, we'll help you get back on track quickly and accurately."
                    />
                    <Check
                      title="We'll do the hard work for you"
                      details='Get peace of mind with our team of experts and your dedicated bookkeeper working together to complete your overdue books accurately, with regular reviews ensuring tax-readiness.'
                    />
                    <Check
                      title='No-frills pricing'
                      details='Like with our other bundles, enjoy stable pricing with Catch Up Bookkeeping starting at $100/month, with no additional charges, hourly rates, upcharges, or hidden fees. Our fixed price structure motivates us to complete the work as fast as possible and our reputation, efficiently.'
                    />
                  </div>
                </div>
              </Group>
              <Group key='second'>
                <div className='border-t border-[#f2f2f2] pt-20 mt-20 flex items-start justify-between w-full'>
                  <div className='max-w-[364px] w-full flex flex-col'>
                    <h3 className='mt-4 text-heading font-bold text-[32px]'>
                      Personalised Experience, just for you
                    </h3>
                    <p className='mt-2 text-body'>
                      Get a personalised experience that's tailored specifically
                      to your business.
                    </p>
                  </div>
                  <div className='flex flex-col max-w-[530px] w-full gap-y-5'>
                    <Check
                      title='Accessible and Secure Records'
                      details="We use state-of-the-art tools to keep your records accessible and secure. You'll have access to your records at any time, from anywhere, and you can rest assured that your data is protected with the latest security protocols."
                    />
                    <Check
                      title='Expert Analysis and Advice'
                      details="In addition to helping you catch up on your accounting records, our team of experienced accountants can also provide expert analysis and advice. We'll help you understand your financial records and provide insights to help you make informed business decisions."
                    />
                    <Check
                      title='Timely Communication and Updates'
                      details="We understand the importance of timely communication and updates when it comes to accounting records. That's why we'll keep you informed throughout the Catch Up Accounting process, providing regular updates on our progress and answering any questions you may have. "
                    />
                  </div>
                </div>
              </Group>
              <Group key='third'>
                <div className='border-t border-[#f2f2f2] pt-20 mt-20 flex items-start justify-between w-full'>
                  <div className='max-w-[364px] w-full flex flex-col'>
                    <h3 className='mt-4 text-heading font-bold text-[32px]'>
                      Year-End Financial Package
                    </h3>
                    <p className='mt-2 text-body'>
                      Let’s handle your catch up and we will give you a year-end
                      financial package for each year of catch up.
                    </p>
                  </div>
                  <div className='flex flex-col max-w-[530px] w-full gap-y-5'>
                    <Check
                      title='All your reports in one place'
                      details='Say goodbye to scattered financial documents - our Year End Financial Package includes your IFRS compliant income statement, balance sheet, statement of cash flows, and notes to the accounts, all in one place.'
                    />
                    <Check
                      title='Tax-Ready Documentation'
                      details='Our Year End Financial Package includes tax-ready documentation, making it easy to file your taxes and avoid accumulating penalties for missed deadlines. Our expert team ensures that all documentation is accurate and complete, so you can file with confidence.'
                    />
                    <Check
                      title='Organised and Efficient'
                      details='Our Year End Financial Package is designed to make catching up on years of financial records as efficient and organised as possible making it easy for you to understand your financial situation.'
                    />
                  </div>
                </div>
              </Group>
            </Group>
          </div>
        </div>
      </Group>
      <SupportCard />
      <Testimonials />
    </div>
  );
}
