/* eslint-disable @next/next/no-img-element */
import { Group, SectionHeading, SupportCard, Testimonials } from '~/components';
import { Figtree } from 'next/font/google';
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Tax Advisory | Accountable',
  description: 'Generated by create next app',
};
const figtree = Figtree({ subsets: ['latin'] });

export default function Tax() {
  return (
    <div
      className={[figtree.className, 'flex min-h-screen flex-col pt-24'].join(
        ' '
      )}
    >
      <Group key='home-hero'>
        <div className='pt-24 pb-[120px] max-w-[1230px] mx-auto'>
          <div className='grid grid-cols-2 w-full items-center'>
            <div className='flex flex-col'>
              <p className='text-midnight'>Tax Filling and Advisory</p>
              <h1 className='text-heading text-5xl leading-snug mt-2 max-w-[607px] font-bold'>
                Get year-round tax advisory, support and your filings done on
                time.
              </h1>
              <p className='mt-4 max-w-[460px] text-body'>
                Tax returns don’t need to be stressful. We’ll sort your taxes
                for you whether current or backlog. We’ve saved our clients over{' '}
                <span className='text-span-5'>N9.35bn</span> in taxes
                <br />‍<br />
                Simple, fast, all online
                <br />
                Sorted by an accredited tax expert
              </p>

              <div className='mt-10 flex items-center gap-x-4'>
                <a
                  href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                  target='_blank'
                  className='bg-midnight text-white py-3 px-6 rounded-xl'
                >
                  Book a meeting
                </a>
              </div>
            </div>
            <div>
              <img
                src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp.png'
                loading='lazy'
                width='682'
                sizes='(max-width: 767px) 100vw, 682px'
                alt=''
                srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp-p-1080.png 1080w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp.png 1364w'
              />
            </div>
          </div>
        </div>
      </Group>

      <SupportCard />
      <Testimonials />
    </div>
  );
}
