/* eslint-disable @next/next/no-img-element */
import { Metadata } from 'next';
import { Figtree } from 'next/font/google';

import { FeaturedIn, Group, SupportCard, VisionPane } from '~/components';
export const metadata: Metadata = {
  title: 'About Us | Accountable',
  description: 'Generated by create next app',
};
const figtree = Figtree({ subsets: ['latin'] });

export default function AboutUs() {
  return (
    <div
      className={[figtree.className, 'flex min-h-screen flex-col pt-24'].join(
        ' '
      )}
    >
      <Group key='home-hero'>
        <div className='pt-24 flex flex-col items-center'>
          <div className='flex flex-col items-center text-center'>
            <h1 className='text-[#1d1e20] font-bold text-[64px] max-w-[720px] leading-tight'>
              We are Accountable, your trusted advisers
            </h1>
          </div>
        </div>
      </Group>
      <Group key='image galler'>
        <div className='px-4 mt-[120px]'>
          <img
            src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery.png'
            loading='lazy'
            srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-1080.png 1080w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-1600.png 1600w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-2000.png 2000w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-2600.png 2600w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery.png 2848w'
            sizes='(max-width: 479px) 93vw, (max-width: 767px) 92vw, (max-width: 991px) 94vw, (max-width: 2906px) 98vw, 2848px'
            alt=''
          />
        </div>
      </Group>
      <Group key='who we are'>
        <div className='max-w-[1240px] mx-auto mt-[184px] pb-12'>
          <div className='flex items-start justify-between'>
            <div className='max-w-[467px]'>
              <div className='w-fit text-sm border rounded-full text-midnight border-midnight py-1 px-3 font-medium'>
                WHO WE ARE
              </div>
              <h1 className='text-heading text-[40px] font-bold mt-1'>
                A nonpareil team of finance experts
              </h1>
            </div>
            <div className='max-w-[690px] text-body font-medium'>
              <p className='who-we-are-paragraph'>
                We are a nonpareil team of professionals providing high
                value-added accounting, tax, compliance, process improvement and
                financial advisory services to growth-focused businesses.
                <br />
                <br />
                Our high-touch service, practical advisory, customised
                experience and a competitive fee structure supports and allows
                you to succeed during each stage of your business’ lifecycle by
                providing detailed highlights into your finances which will in
                turn improve your financial process and business performance.
                <br />
                <br />
                Combining technology and astute local knowledge with the global
                expertise of our most senior professionals, you are sure to
                enjoy the same seamless service wherever you are in the world.
                <br />
              </p>
            </div>
          </div>
        </div>
      </Group>
      <VisionPane />
      <Group key='values'>
        <div className='pt-24 w-full'>
          <div className='max-w-[940px] mx-auto w-full flex flex-col py-[72px] items-center'>
            <Group key='heading '>
              <div className='mt-5 flex flex-col items-center'>
                <h1 className='text-heading  font-bold text-[38px] '>
                  Some of our values
                </h1>
                <p className='text-sm text-[#333] mt-[10px]'>
                  Our values guides us, and reflects in our dealings
                </p>
              </div>
            </Group>
            <Group key='grid'>
              <div className='grid grid-cols-2 mt-20 gap-x-[84px] gap-y-14 max-w-[836px]'>
                <div className='py-6 px-8 rounded-[1rem] bg-[#e8f3fe]'>
                  <div>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/640a13b6aa67852ce5c7d775_service.png'
                      loading='lazy'
                      width='48'
                      alt=''
                    />
                  </div>
                  <div className='flex flex-col mt-6 gap-y-[10px]'>
                    <h1 className='font-bold text-2xl text-heading'>Service</h1>
                    <p className='text-body text-lg pb-6'>
                      We are committed to providing exceptional service to our
                      clients. We take a client-first approach and work closely
                      with them to understand their unique needs and tailor our
                      solutions to their specific challenges.
                    </p>
                  </div>
                </div>
                <div className='py-6 px-8 rounded-[1rem] bg-[#edfaf3]'>
                  <div>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/640a13b63e57290404493c36_Frame%20427319348.png'
                      loading='lazy'
                      width='48'
                      alt=''
                    />
                  </div>
                  <div className='flex flex-col mt-6 gap-y-[10px]'>
                    <h1 className='font-bold text-2xl text-heading'>
                      Integrity
                    </h1>
                    <p className='text-body text-lg pb-6'>
                      We operate with the highest level of integrity and uphold
                      the ethical standards of our profession. Our clients trust
                      us to provide honest and transparent advice, and we take
                      that responsibility seriously.
                    </p>
                  </div>
                </div>
                <div className='py-6 px-8 rounded-[1rem] bg-[#f6e8f4]'>
                  <div>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/640a13b674015c58bbb05698_Frame%20427319344.png'
                      loading='lazy'
                      alt=''
                      width='48'
                    />
                  </div>
                  <div className='flex flex-col mt-6 gap-y-[10px]'>
                    <h1 className='font-bold text-2xl text-heading'>
                      Technology for efficiency
                    </h1>
                    <p className='text-body text-lg pb-6'>
                      We leverage the latest technology, data analytics tools,
                      and the most complex technology - the human brain, to
                      optimise our clients’ operations, improve their
                      performance and provide them with the insights they need
                      to make informed business decisions
                    </p>
                  </div>
                </div>
                <div className='py-6 px-8 rounded-[1rem] bg-[#eef1fe]'>
                  <div id='w-node-d79236a0-740c-3b39-c676-0bbc38d98084-2a5596a1'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/640a13b6f4752690f85545b0_Frame%20427319345.png'
                      loading='lazy'
                      alt=''
                      width='48'
                    />
                  </div>
                  <div className='flex flex-col mt-6 gap-y-[10px]'>
                    <h1 className='font-bold text-2xl text-heading'>
                      People-centred
                    </h1>
                    <p className='text-body text-lg pb-6'>
                      We prioritise the well-being of our employees and clients,
                      we are deeply invested in the communities we serve. Our
                      community-driven approach ensures we build lasting
                      relationships with our clients and provide them with the
                      resources they need to succeed.
                    </p>
                  </div>
                </div>
              </div>
            </Group>
          </div>
        </div>
      </Group>
      <Group key='with us'>
        <div
          style={{ backgroundImage: 'url(/faqsbg.png)' }}
          className='mt-[120px] py-[64px] bg-cover bg-center text-white'
        >
          <div className='max-w-[960px] mx-auto flex flex-col items-center'>
            <div className='flex flex-col items-center'>
              <h4 className='text-xs border border-[#868ca6] text-[#868ca6] py-1 px-[10px] rounded-full w-fit'>
                WORK WITH US
              </h4>
              <h1 className='text-[40px] font-medium text-center leading-tight mt-8'>
                At Accountable, we are helping businesses and individuals stay
                on top of their financial accounting goals. Join the winning
                team{' '}
              </h1>
              <a
                href='https://www.linkedin.com/company/weareaccountable/'
                target='_blank'
                className='py-3 px-6 rounded-xl bg-[#d9a01b] text-white mt-12'
              >
                View all open roles
              </a>
            </div>
          </div>
        </div>
      </Group>
      <div className='flex flex-col gap-y-[96px]'>
        <FeaturedIn />
        <SupportCard />
      </div>
    </div>
  );
}
