/* eslint-disable @next/next/no-img-element */
import { Metadata } from 'next';
import { FeaturedIn, Group, SupportCard } from '~/components';
export const metadata: Metadata = {
  title: 'About Us | Accountable',
  description: 'Generated by create next app',
};
export default function AboutUs() {
  return (
    <div className='flex min-h-screen flex-col pt-24'>
      <Group key='home-hero'>
        <div className='pt-24 flex flex-col items-center'>
          <div className='flex flex-col items-center text-center'>
            <h1 className='text-[#1d1e20] font-bold text-[64px] max-w-[720px] leading-tight'>
              We are Accountable, your trusted advisers
            </h1>
          </div>
        </div>
      </Group>
      <Group key='image galler'>
        <div className='px-4 mt-[120px]'>
          <img
            src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery.png'
            loading='lazy'
            srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-1080.png 1080w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-1600.png 1600w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-2000.png 2000w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery-p-2600.png 2600w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e6de5e42d3132405a5bb7_work-gallery.png 2848w'
            sizes='(max-width: 479px) 93vw, (max-width: 767px) 92vw, (max-width: 991px) 94vw, (max-width: 2906px) 98vw, 2848px'
            alt=''
          />
        </div>
      </Group>
      <Group key='who we are'>
        <div className='max-w-[1240px] mx-auto mt-[184px] pb-12'>
          <div className='flex items-start justify-between'>
            <div className='max-w-[467px]'>
              <div className='w-fit text-sm border rounded-full text-midnight border-midnight py-1 px-3 font-medium'>
                WHO WE ARE
              </div>
              <h1 className='text-heading text-[40px] font-bold mt-1'>
                A nonpareil team of finance experts
              </h1>
            </div>
            <div className='max-w-[690px] text-body font-medium'>
              <p className='who-we-are-paragraph'>
                We are a nonpareil team of professionals providing high
                value-added accounting, tax, compliance, process improvement and
                financial advisory services to growth-focused businesses.
                <br />
                <br />
                Our high-touch service, practical advisory, customised
                experience and a competitive fee structure supports and allows
                you to succeed during each stage of your business’ lifecycle by
                providing detailed highlights into your finances which will in
                turn improve your financial process and business performance.
                <br />
                <br />
                Combining technology and astute local knowledge with the global
                expertise of our most senior professionals, you are sure to
                enjoy the same seamless service wherever you are in the world.
                <br />
              </p>
            </div>
          </div>
        </div>
      </Group>
      <FeaturedIn />
      <SupportCard />
    </div>
  );
}
