/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import { Metadata } from 'next';
import { Group, SectionHeading, SupportCard, Testimonials } from '~/components';

export const metadata: Metadata = {
  title: 'Accountable PISP | Accountable',
  description: 'Generated by create next app',
};
export default function AccPISP() {
  return (
    <div className='flex min-h-screen flex-col pt-24'>
      <Group key='home-hero'>
        <div className='pt-24 pb-[120px] max-w-[1230px] mx-auto'>
          <div className='grid grid-cols-2 w-full items-center'>
            <div className='flex flex-col'>
              <p className='text-midnight'>
                Process Improvement or Succession Planning?
              </p>
              <h1 className='text-heading text-5xl mt-2 max-w-[607px] font-bold'>
                Drive Success Through Efficient Processes
              </h1>
              <p className='mt-4 max-w-[460px] text-body'>
                At the heart of a successful long term business is a well-oiled
                process. Say goodbye to inefficiencies and hello to streamlined
                workflows with our process improvement services.
              </p>
              <div className='mt-10 flex items-center gap-x-4'>
                <a
                  href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                  target='_blank'
                  className='bg-midnight text-white py-3 px-6 rounded-xl'
                >
                  Book a meeting
                </a>
                <a
                  href='#'
                  className='border border-midnight text-midnight py-3 px-6 rounded-xl'
                >
                  Watch a demo
                </a>
              </div>
            </div>
            <div id='w-node-c5948e4b-7bb8-3bce-154b-b822a3b67dbd-3e938eec'>
              <img
                src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp.png'
                loading='lazy'
                width='682'
                sizes='(max-width: 767px) 100vw, 682px'
                alt=''
                srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp-p-1080.png 1080w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641d97ade7fcfb6de8a0a32b_img_pisp.png 1364w'
              />
            </div>
          </div>
        </div>
      </Group>
      <Group key='how it works'>
        <div className='mt-[120px] bg-[#f7f9fb]'>
          <div className='pt-[120px] pb-[160px] max-w-[1230px] mx-auto'>
            <div className='flex flex-col items-center'>
              <div className='flex flex-col items-center'>
                <h4 className='text-sm text-midnight border border-midnight py-1 px-[10px] rounded-full w-fit'>
                  HOW IT WORKS
                </h4>
                <h1 className='text-[40px] max-w-[620px] font-bold text-center leading-tight mt-4'>
                  How Accountable PISP works{' '}
                </h1>
                <p className='text-xl text-[#575e66] max-w-[620px] text-center mt-[10px]'>
                  Finance for businesses, powered by real humans. We work round
                  the clock to assist you with anything you need.
                </p>
              </div>
              <Group key='grided'>
                <div className='grid grid-cols-2 gap-x-6 gap-y-8 max-w-[924px] mt-20'>
                  <GridCard
                    id='01'
                    title='Analysis'
                    details='We start by analyzing your current processes to identify
                      areas that needs to be optimized and improved.'
                  />
                  <GridCard
                    id='02'
                    title='Planning'
                    details=' We work with you to develop a customized process
                      improvement plan that meets your specific goals and needs.'
                  />
                  <GridCard
                    id='03'
                    title='Implementation'
                    details=' We help you implement your process improvement plan,
                      providing support and guidance every step of the way.'
                  />
                  <GridCard
                    id='04'
                    title='Monitoring'
                    details=' We continue to monitor your processes after implementation
                      to ensure continuous improvement and success.'
                  />
                </div>
              </Group>
              <div className='mt-[80px]'>
                <a
                  href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                  target='_blank'
                  className='bg-midnight text-white py-3 px-4 rounded-xl block'
                >
                  Book a meeting
                </a>
              </div>
            </div>
          </div>
        </div>
      </Group>
      <Group key='accountable pisp'>
        <div className='mt-[120px] '>
          <div className=' pb-[80px] max-w-[1230px] mx-auto flex flex-col items-center'>
            <SectionHeading
              title='ACCOUNTABLE PISP'
              heading="Here's what we will do for you"
              paragraph='Finance for businesses, powered by real humans. We work round the clock to assist you with anything you need.'
            />
            <div className='flex items-center justify-between max-w-[965px] w-full mt-20'>
              <div className='shrink-0'>
                <img
                  src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/64108888356436a55c7c8e10_pisp-service_img.png'
                  loading='lazy'
                  width='525'
                  sizes='(max-width: 479px) 100vw, (max-width: 767px) 52vw, (max-width: 991px) 54vw, 525px'
                  alt=''
                  srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/64108888356436a55c7c8e10_pisp-service_img-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/64108888356436a55c7c8e10_pisp-service_img-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/64108888356436a55c7c8e10_pisp-service_img.png 1050w'
                />
              </div>
              <div className='max-w-[360px] flex flex-col gap-y-10'>
                <div className='flex flex-col gap-y-2'>
                  <h1 className='text-heading'>Process Mapping</h1>
                  <p className='text-sm text-body'>
                    Identify inefficiencies and bottlenecks in your current
                    processes with detailed process maps that illustrate each
                    step of your workflows
                  </p>
                </div>
                <div className='flex flex-col gap-y-2'>
                  <h1 className='text-heading'>Process Redesign</h1>
                  <p className='text-sm text-body'>
                    Our team can help you redesign your processes to eliminate
                    waste, reduce errors, and improve overall efficiency.
                  </p>
                </div>
                <div className='flex flex-col gap-y-2'>
                  <h1 className='text-heading'>Process Automation</h1>
                  <p className='text-sm text-body'>
                    Let us help you automate repetitive tasks and integrate
                    systems to improve data accuracy and reduce manual labour.
                  </p>
                </div>
                <div className='flex flex-col gap-y-2 last'>
                  <h1 className='text-heading'>Process Optimization</h1>
                  <p className='text-sm text-body'>
                    Our consultants will help you become more productive and
                    profitable by optimising your processes while being
                    compliant
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Group>
      <Group key='benefits'>
        <div className='mt-[120px] bg-[#fcfeff]'>
          <div className=' pb-[80px] max-w-[1230px] mx-auto flex flex-col items-center'>
            <SectionHeading
              title='BENEFITS'
              heading='Some benefits of this service includes'
              paragraph='Finance for businesses, powered by real humans. We work round the clock to assist you with anything you need.'
            />
            <div className='flex flex-col items-center justify-between max-w-[976px] w-full mt-[82px]'>
              <Group key='benefits grid'>
                <div className='flex items-center justify-between w-full'>
                  <div className='max-w-[220px] flex flex-col items-center gap-y-6 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641046491dac1e6b91b6f25f_efficiency%201.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className='text-lg text-heading font-semibold'>
                      Measurable Increase In Efficiency
                    </div>
                  </div>
                  <div className='max-w-[220px] flex flex-col items-center gap-y-6 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641046479aa3996f80d15b22_Group.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className='text-lg text-heading font-semibold'>
                      Improvement In Decision Making
                    </div>
                  </div>
                  <div className='max-w-[220px] flex flex-col items-center gap-y-6 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641046479aa3996f80d15b22_Group.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className='text-lg text-heading font-semibold'>
                      Long Term Business Success
                    </div>
                  </div>
                  <div className='max-w-[220px] flex flex-col items-center gap-y-6 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/641046479aa3996f80d15b22_Group.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className='text-lg text-heading font-semibold'>
                      Effective &amp; Efficiently Saves Cost.
                    </div>
                  </div>
                </div>
              </Group>
              <Group key='cta'>
                <div className='mt-[72px] flex items-center gap-x-4'>
                  <a
                    href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                    target='_blank'
                    className='bg-midnight text-white py-3 px-6 rounded-xl'
                  >
                    Book a meeting
                  </a>
                  <a
                    href='#'
                    className='border border-midnight text-midnight py-3 px-6 rounded-xl'
                  >
                    Watch a demo
                  </a>
                </div>
              </Group>
            </div>
          </div>
        </div>
      </Group>
      <Group key='smiley'>
        <div className='py-[120px]'>
          <div className=' max-w-[1230px] mx-auto flex justify-between items-center'>
            <Group key='extra notes'>
              <div className='max-w-[560px] w-full'>
                <h1 className='font-bold text-2xl leading-tight text-heading'>
                  How we explain process improvement to a five year old+
                </h1>
                <p className='text-sm text-body mt-6'>
                  Financial process improvement is like cleaning up a messy
                  room. Just like how you might clean up your toys and put them
                  away in the right places, companies need to organise and
                  improve their financial processes to make sure everything is
                  in the right place and works properly.
                  <br />
                  <br />
                  For example, let's say a company needs to pay its bills every
                  month. If they don't have a good process in place, they might
                  forget to pay a bill or pay it twice by mistake. This can be
                  messy and cost the company extra money! but if they have a
                  good financial process in place, they can keep track of all
                  their bills and payments, making sure everything is paid on
                  time and without any mistakes. This can save the company time
                  and money, and help them be more successful.
                  <br />
                  <br />
                  So, financial process improvement is all about making sure
                  that a company's financial processes are organised, efficient,
                  and work properly, just like how you clean up your room to
                  make sure everything is in the right place and easy to find.
                </p>
              </div>
            </Group>
            <Group key='smile image'>
              <div className='max-w-[395px] w-full'>
                <img
                  src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6422af8fb097f5e918d54f77_fiveyearold.png'
                  loading='lazy'
                  width='395'
                  sizes='(max-width: 479px) 100vw, (max-width: 767px) 35vw, (max-width: 991px) 36vw, 37vw'
                  alt=''
                  srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6422af8fb097f5e918d54f77_fiveyearold-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6422af8fb097f5e918d54f77_fiveyearold.png 790w'
                />
              </div>
            </Group>
          </div>
        </div>
      </Group>
      <Group key='succession'>
        <div
          style={{ backgroundImage: 'url(/faqsbg.png)' }}
          className='mt-10 py-24 bg-cover bg-center text-white'
        >
          <div className='max-w-[910px] mx-auto flex flex-col items-center'>
            <div className='flex flex-col items-center'>
              <h1 className='text-[40px] max-w-[620px] font-bold text-center leading-tight mt-4'>
                Planning exit/succession?
              </h1>
              <p className='text-xl max-w-[640px] text-[#b5b5b5] text-center mt-[10px]'>
                Here, we want to talk about our current open roles if we have
                any, or also use this box to talk about why any talent should
                join our team.
              </p>
              <a
                href='#'
                className='py-3 px-6 rounded-xl bg-[#d9a01b] text-white mt-[42px]'
              >
                Contact sales
              </a>
            </div>
          </div>
        </div>
      </Group>
      <SupportCard />
      <Testimonials />
    </div>
  );
}

const GridCard = ({
  id,
  title,
  details,
}: {
  id: string;
  details: string;
  title: string;
}) => {
  return (
    <div className='flex flex-col p-6 rounded-lg border border-[#e8ecfc] bg-white'>
      <div className='w-10 h-10 rounded-full flex items-center justify-center border-[#8a9ff2] text-[#8a9ff2] border'>
        <div className='text-block-16'>{id}</div>
      </div>
      <h1 className='mt-3 font-semibold text-heading'>{title}</h1>
      <p className='text-body text-sm mt-2'>{details}</p>
    </div>
  );
};
