import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer, MobileNav, NavBar, ScrollingNav } from '~/components';
import { MobileFooter } from '~/components/Footer/mobile';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className='relative'>
          <MobileNav />
          <NavBar />
          {/* <div className='w-full hidden fr:block h-[80px]'> */}
          <ScrollingNav />
          {/* </div> */}
        </nav>
        <main id='main'>{children}</main>
        <MobileFooter />
        <Footer />
      </body>
    </html>
  );
}
