/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import { Metadata } from 'next';
import {
  FaqsSection,
  FeaturedIn,
  Group,
  ServiceCard,
  SupportCard,
  Testimonials,
} from '~/components';
export const metadata: Metadata = {
  title: 'Accountable Finance',
  description: 'Generated by create next app',
};
export default function Home() {
  const services = [
    {
      'imageSrc':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6409ac90d83697efab4ce90c_PISP.png',
      'srcSet':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6409ac90d83697efab4ce90c_PISP-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6409ac90d83697efab4ce90c_PISP.png 660w',
      'title': 'Accountable PISP',
      'text':
        'Process Improvement or Succession Planning? We’ve got you covered',
      'url': '/accountable-pisp',
    },
    {
      'imageSrc':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b2087780a7e1e10a7387_Bookkeeping.png',
      'srcSet':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b2087780a7e1e10a7387_Bookkeeping-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b2087780a7e1e10a7387_Bookkeeping.png 660w',
      'title': 'Monthly Bookkeeping',
      'text':
        'Get a dedicated accountant. Start tracking your finances like a pro today.',
      'url': '/bookkeeping',
    },
    {
      'imageSrc':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b4a3b8c50c852c25845a_Tax.png',
      'srcSet':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b4a3b8c50c852c25845a_Tax-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b4a3b8c50c852c25845a_Tax.png 660w',
      'title': 'Tax Filling &amp;&nbsp;Advisory',
      'text':
        'Get year-round tax advisory, support and your filings done on time.',
      'url': '/tax',
    },
    {
      'imageSrc':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b5c639bebb8a5d77e295_Accounting.png',
      'srcSet':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b5c639bebb8a5d77e295_Accounting-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b5c639bebb8a5d77e295_Accounting.png 660w',
      'title': 'Accountable FMCC',
      'text':
        'Specifically designed for creatives - music artists, producers, influencers',
      'url': '/accountable-fmcc',
    },
    {
      'imageSrc':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b6cd31ea2be63ec2cf80_creative.png',
      'srcSet':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b6cd31ea2be63ec2cf80_creative-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b6cd31ea2be63ec2cf80_creative.png 660w',
      'title': 'Catchup Accounting',
      'text':
        "Are you behind on your bookkeeping for two years or less? Let's Catchup!",
      'url': '/catchup-bookkeeping',
    },
    {
      'imageSrc':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b66bd83119b149dda544_Accounting2.png',
      'srcSet':
        'https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b66bd83119b149dda544_Accounting2-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408b66bd83119b149dda544_Accounting2.png 660w',
      'title': 'Retroactive Accounting',
      'text':
        'More than two years behind? Backlog tax issues too? This is for you',
      'url': '/retrospective-bookkeeping',
    },
  ];

  return (
    <main className='flex min-h-screen flex-col  pt-24'>
      <Group key='home-hero'>
        <div className='pt-10 px-6 md:px-0 md:pt-24 flex flex-col md:items-center'>
          <div className='flex flex-col md:items-center md:text-center'>
            <h1 className='text-[#1d1e20] font-bold md:font-black text-3xl md:text-7xl max-w-[720px]'>
              Optimize your financial processes
            </h1>
            <p className='text-[#575e66] font-medium md:font-bold max-w-[680px] mt-4 text-sm md:text-xl'>
              We're here to help you every step of the way - from optimising
              your financial processes to managing bookkeeping and taxes
            </p>
            <div className='flex flex-col mt-12'>
              <a
                href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                target='_blank'
                className='bg-[#001b84] py-3 px-4 rounded-xl text-white max-md:w-fit'
              >
                Book a meeting now
              </a>
            </div>
            <div className='text-block-21 mt-3'>It's completely free!</div>
          </div>
          <img
            src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/64077b54ef0fa04740839061_hero_img.png'
            loading='lazy'
            sizes='(max-width: 479px) 100vw, 990px'
            // width='990'
            alt='Hero Image'
            className='mt-10 md:w-[990px]'
          />
        </div>
      </Group>
      <Group key='home-brands'>
        <div className='wrapper mx-auto pt-6 md:pt-14 pb-10 md:pb-[88px]'>
          <div className='flex flex-col max-w-[1020px]'>
            <div className='flex items-center justify-between gap-x-14'>
              <span className='h-[1px] max-md:hidden  border border-[#001b84] max-w-[380px] block w-full'></span>
              <div className='shrink-0'>
                Helping proactive brands secure their future
              </div>
              <span className='h-[1px] max-md:hidden border border-[#001b84] max-w-[380px] block w-full'></span>
            </div>
            <Group key='images'>
              <div className='flex items-center gap-x-4 md:gap-x-8 mt-10 md:mt-16 max-md:grid grid-cols-2 gap-y-6 max-md:px-6'>
                <a
                  href='https://www.nguvuhealth.com/'
                  target='_blank'
                  className='w-inline-block'
                >
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642db5545dcdd0ef983b3de7_nguvu.png'
                    loading='lazy'
                    width='151'
                    alt="Brands we've worked for"
                  />
                </a>
                <a
                  href='https://www.synlab.com.ng/'
                  target='_blank'
                  className='w-inline-block'
                >
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642db5551db0d9922caac882_synlab.png'
                    loading='lazy'
                    width='142'
                    alt="Brands we've worked for"
                  />
                </a>
                <div>
                  <a
                    href='https://bogobiri.com/'
                    target='_blank'
                    className='w-inline-block'
                  >
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642db555b19bd657d90166bb_bogobiri.png'
                      loading='lazy'
                      width='48'
                      alt="Brands we've worked for"
                    />
                  </a>
                </div>
                <a
                  href='https://afnigeria.org/'
                  target='_blank'
                  className='w-inline-block'
                >
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642db5546368423129825884_alliance.png'
                    loading='lazy'
                    width='80'
                    alt=''
                  />
                </a>
                <a
                  href='https://spottr.app/'
                  target='_blank'
                  className='w-inline-block'
                >
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642db555a1d33154734ee2cf_spottr.png'
                    loading='lazy'
                    width='143'
                    alt="Brands we've worked for"
                  />
                </a>
                <a
                  href='https://cometoidesign.com/'
                  target='_blank'
                  className='w-inline-block'
                >
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642db555d9658a58a50d9915_idesign.png'
                    loading='lazy'
                    width='138.5'
                    id='w-node-_3e2f2884-2880-7f8d-bc14-12ba34107dae-4c7c6952'
                    alt="Brands we've worked for"
                  />
                </a>
              </div>
            </Group>
          </div>
        </div>
      </Group>
      <Group key='services'>
        <div className='py-10 md:py-20'>
          <div className='max-w-[1028px] mx-auto max-md:px-6'>
            <div className='flex flex-col md:items-center'>
              <h4 className='text-sm text-midnight border border-midnight py-1 px-[10px] rounded-full w-fit'>
                OUR SERVICES
              </h4>
              <h1 className='text-2xl md:text-[40px] max-w-[620px] font-semibold md:font-black md:text-center leading-tight mt-4'>
                We can help you and your team achieve much more
              </h1>
              <p className='text-sm md:text-xl text-[#575e66] max-w-[620px] md:text-center mt-[10px]'>
                With our customised solutions, you can trust that your finances
                are in good hands, so you can focus on running your business and
                improving your bottom line.
              </p>
            </div>
            <div className='grid grid-cols-2 md:grid-cols-3 gap-x-10 gap-y-8 mt-[88px]'>
              {services.map((service) => (
                <ServiceCard key={service.title} {...service} />
              ))}
            </div>
          </div>
        </div>
      </Group>
      <Group key='processes'>
        <div className='mt-20 md:mt-30 py-16 md:py-24 bg-[#f8fafe]'>
          <div className='max-w-[1200px] mx-auto max-md:px-6'>
            <div className='flex flex-col md:items-center'>
              <h4 className='text-sm text-midnight border border-midnight py-1 px-[10px] rounded-full w-fit'>
                OUR PROCESS
              </h4>
              <h1 className='text-2xl md:text-[40px] max-w-[620px] font-semibold md:font-black md:text-center leading-tight mt-4'>
                Here's how we love to work
              </h1>
              <p className='text-sm md:text-xl text-[#575e66] max-w-[620px] md:text-center mt-[10px]'>
                Over the years, we have perfected our work process that allows
                us help businesses reach their full potential
              </p>
            </div>
            <div className='mt-20 md:mt-[120px] gap-x-10 flex max-md:flex-col items-center'>
              <div className='div-block-46 shrink-0'>
                <img
                  src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408a5c97fd405dd86deb79e_processNew_image.png'
                  loading='lazy'
                  sizes='(max-width: 479px) 343px, (max-width: 991px) 400px, 640px'
                  width='640'
                  alt=''
                  srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408a5c97fd405dd86deb79e_processNew_image-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408a5c97fd405dd86deb79e_processNew_image-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408a5c97fd405dd86deb79e_processNew_image-p-1080.png 1080w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6408a5c97fd405dd86deb79e_processNew_image.png 1278w'
                  className='w-auto md:w-[640px]'
                />
              </div>
              <div className='flex flex-col gap-y-10'>
                <div>
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642d8b977499632ba517eaa2_discovery.png'
                    loading='lazy'
                    alt=''
                    width='36'
                  />
                  <h1 className='text-heading font-semibold mt-5'>DISCOVERY</h1>
                  <p className='text-sm text-body mt-2'>
                    We get to know more about you and your business, your staff
                    strength, challenges encountered in the past your history
                    and also your current needs.
                  </p>
                </div>
                <div className='div-block-16'>
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642d8b973be9f81cc71895c4_design.png'
                    loading='lazy'
                    alt=''
                    width='36'
                  />
                  <h1 className='text-heading font-semibold mt-5'>
                    ASSESS&nbsp;&amp;&nbsp;DESIGN
                  </h1>
                  <p className='text-sm text-body mt-2'>
                    At this stage, we compare your current state with your short
                    &amp; long term vision, after which our team will brainstorm
                    to design a custom solution that works just for you.
                  </p>
                </div>
                <div className='div-block-132'>
                  <img
                    src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642d8b971d2685c2ed2a692b_implement.png'
                    loading='lazy'
                    alt=''
                    width='36'
                  />
                  <h1 className='text-heading font-semibold mt-5'>
                    IMPLEMENT&nbsp;&amp;&nbsp;MONITOR
                  </h1>
                  <p className='text-sm text-body mt-2'>
                    We implement, monitor and tweak as required. We take
                    feedback from you, iterate accordingly and measure success
                    and impact
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Group>
      <Group key='number'>
        <div className='mt-[96px] mb-[120px]'>
          <div className='bg-[#fafafa] max-w-[1260px] border border-[#eaeaea] rounded-lg mx-auto py-4 px-14 gap-y-8 md:px-[82px] flex max-md:grid grid-cols-1 items-center md:justify-between'>
            <div className='flex flex-col'>
              <h1 className='text-[32px] md:text-[52px] font-bold text-heading'>
                65yrs+
              </h1>
              <div className='text-sm text-body md:mt-6'>
                COMBINED MGT. EXPERIENCE
              </div>
            </div>
            <div className='max-md:hidden w-[1px] border border-[#eaeaea] bg-[#eaeaea] h-[133px]'></div>
            <div className='div-block-49'>
              <h1 className='text-[32px] md:text-[52px] font-bold text-heading'>
                60+
              </h1>
              <div className='text-sm text-body md:mt-6'>HAPPY CUSTOMERS</div>
            </div>
            <div className='max-md:hidden w-[1px] border border-[#eaeaea] bg-[#eaeaea] h-[133px]'></div>
            <div className='div-block-50'>
              <h1 className='text-[32px] md:text-[52px] font-bold text-heading'>
                4+
              </h1>
              <div className='text-sm text-body md:mt-6'>COUNTRIES</div>
            </div>
            <div className='max-md:hidden w-[1px] border border-[#eaeaea] bg-[#eaeaea] h-[133px]'></div>
            <div className='div-block-51'>
              <h1 className='text-[32px] md:text-[52px] font-bold text-heading'>
                91.7%
              </h1>
              <div className='text-sm text-body md:mt-6'>
                CUSTOMER RETENTION
              </div>
            </div>
          </div>
        </div>
      </Group>
      <Testimonials />
      <FeaturedIn />
      <div className='mt-10 mb-10'></div>
      <SupportCard />
      <FaqsSection />
    </main>
  );
}
