/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import { Metadata } from 'next';
import {
  Check,
  Group,
  SectionHeading,
  SupportCard,
  Testimonials,
} from '~/components';
import { Figtree } from 'next/font/google';
import Link from 'next/link';
const figtree = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Retrospective Bookkeeping | Accountable',
  description: 'Generated by create next app',
};
export default function RetroBkk() {
  return (
    <div
      className={[
        figtree.className,
        'flex min-h-screen flex-col pt-10 md:pt-24',
      ].join(' ')}
    >
      <Group key='home-hero'>
        <div className='pt-16 md:pt-24 pb-20 md:pb-[120px] max-w-[1230px] mx-auto max-md:px-6'>
          <div className=' grid max-md:flex flex-col grid-cols-2 w-full items-center'>
            <div className='flex flex-col max-md:items-center max-md:text-center'>
              <p className='text-midnight'>Retroactive Bookkeeping.</p>
              <h1 className='text-heading text-3xl md:text-5xl leading-none md:leading-snug mt-2 max-w-[607px] font-bold'>
                Tidy up your financial records with Catch Up Bookkeeping.
              </h1>
              <p className='mt-4 max-w-[460px] text-body'>
                Don't let overdue bookkeeping stress you out. With Accountable,
                you can get your books up-to-date and ready for filing quickly
                with the help of our expert bookkeepers.
                <br />
                <br />
                For businesses that are more than two years behind on your books
                and taxes.
                <br />
              </p>

              <div className='mt-10 flex items-center gap-x-4'>
                <a
                  href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                  target='_blank'
                  className='bg-midnight text-white py-3 px-6 rounded-xl'
                >
                  Book a meeting
                </a>
                <a
                  href='#'
                  className='border border-midnight text-midnight py-3 px-6 rounded-xl'
                >
                  Watch a demo
                </a>
              </div>
            </div>
            <div className='mt-20'>
              <img
                src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e95f90c8e507e02de582c_retroactive-acc.png'
                loading='lazy'
                width='488'
                sizes='(max-width: 479px) 100vw, (max-width: 767px) 93vw, 488px'
                alt=''
                srcSet='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e95f90c8e507e02de582c_retroactive-acc-p-500.png 500w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e95f90c8e507e02de582c_retroactive-acc-p-800.png 800w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e95f90c8e507e02de582c_retroactive-acc-p-1080.png 1080w, https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642e95f90c8e507e02de582c_retroactive-acc.png 1361w'
              />
            </div>
          </div>
        </div>
      </Group>

      <Group key='benefits'>
        <div className='mt-[120px] bg-[#fcfeff]'>
          <div className=' pb-[80px] max-w-[1230px] mx-auto flex flex-col items-center max-md:px-6'>
            <SectionHeading
              title='BENEFITS'
              heading='Benefits of using Accountable for your bookkeeping'
              paragraph='Finance for businesses, powered by real humans. We work round the clock to assist you with anything you need.'
            />
            <div className='flex flex-col items-center justify-between max-w-[846px] w-full mt-[82px]'>
              <Group key='benefits grid'>
                <div className='max-md:flex-col max-md:gap-y-10 items-center justify-between w-full'>
                  <div className=' flex flex-col items-center gap-y-3 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/642700aa6306fd215d31bd7a_emergency.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className=' text-heading font-semibold'>
                      Emergency support
                    </div>
                    <p className='text-body text-sm'>
                      Letters from the IRS? Years of back taxes to be filed?
                      Missing records? No matter what challenges your business
                      is facing, Accountable Retrospective Accounting has you
                      covered.
                    </p>
                  </div>
                  <div className=' flex flex-col items-center gap-y-3 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6427020c83bb0c51528e4bd7_cheap2.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className=' text-heading font-semibold'>
                      Affordable Payment Plans
                    </div>
                    <p className='text-body text-sm'>
                      We understand that catching up on bookkeeping can be
                      costly. That's why we offer customised packages and
                      flexible payment plans to help make it more manageable.
                    </p>
                  </div>
                  <div className=' flex flex-col items-center gap-y-3 text-center'>
                    <img
                      src='https://assets-global.website-files.com/63fde373aa2d3e5dc97c694e/6426f13db2096d417ae95205_fast.png'
                      loading='lazy'
                      width='56'
                      alt=''
                    />
                    <div className=' text-heading font-semibold'>
                      Swift Turnaround Times
                    </div>
                    <p className='text-body text-sm'>
                      With our efficient service, we can complete months or
                      years of overdue bookkeeping quickly, providing you with
                      more time for your business and less stress associated
                      with deadlines.
                    </p>
                  </div>
                </div>
              </Group>
              <Group key='cta'>
                <div className='mt-[72px] flex items-center gap-x-4'>
                  <a
                    href='https://calendar.app.google/Z9JQd7RHr52r4uoC9'
                    target='_blank'
                    className='bg-midnight text-white py-3 px-6 rounded-xl'
                  >
                    Book a meeting
                  </a>
                  <a
                    href='#'
                    className='border border-midnight text-midnight py-3 px-6 rounded-xl'
                  >
                    Watch a demo
                  </a>
                </div>
              </Group>
            </div>
          </div>
        </div>
      </Group>
      <Group key='features'>
        <div className='mt-20 mb-[120px]'>
          <div className='flex flex-col items-center max-w-[1064px] w-full mx-auto max-md:px-6'>
            <div className='flex flex-col text-center max-w-[620px] pb-20 '>
              <h3 className='text-heading text-2xl md:text-[40px] font-bold leading-tight'>
                Features available to our catchup bookkeeping service
              </h3>
              <p className='text-xl text-body mt-[10px]'>
                Finance for businesses, powered by real humans. We work round
                the clock to assist you with anything you need.
              </p>
            </div>
            <Group key='check grid'>
              <Group key='first'>
                <div className='border-t border-[#f2f2f2] pt-10 md:pt-20 flex max-md:flex-col gap-y-10 items-start justify-between w-full'>
                  <div className='max-w-[364px] w-full flex flex-col'>
                    <h3 className='mt-4 text-heading font-bold text-[32px]'>
                      Catching Up on Your Accounting Records
                    </h3>
                    <p className='mt-2 text-body'>
                      By catching up on your accounting records, you can gain a
                      clear understanding of your finances, avoid penalties,
                      save time and stress, make informed decisions, and receive
                      expert support. Let our team take care of it for you.
                    </p>
                  </div>
                  <div className='flex flex-col max-w-[530px] w-full gap-y-5'>
                    <Check
                      title='Get a Clear Picture of Your Finances'
                      details="By catching up on two or more years of accounting records, you'll be able to see exactly where your money has been going and make informed decisions about your finances."
                    />
                    <Check
                      title='Avoid Additional Penalties and Fees'
                      details="Filing taxes late or incorrectly can lead to penalties and fees. By sorting out your retrospective accounting records, you'll be able to file your taxes accurately and on time, avoiding any unnecessary costs."
                    />
                    <Check
                      title='Save Time and Stress'
                      details='Receiving investigation letters from the tax authorities and trying to catch up on years of accounting records can be overwhelming and stressful. Let our team take care of it for you, saving you time and reducing your stress.'
                    />
                    <Check
                      title='Make Better Financial Decisions'
                      details="With up-to-date financial records, you'll be able to make better financial decisions for your business or personal life. You'll have a clear understanding of your financial situation, allowing you to plan for the future and make informed decisions."
                    />
                    <Check
                      title='Get Expert Support'
                      details="Our team of experienced accountants is here to provide expert support throughout the Catch Up Accounting process. We'll make sure your financial records are accurate and up to date, and we'll answer any questions or concerns you may have along the way."
                    />
                  </div>
                </div>
              </Group>
              <Group key='second'>
                <div className='border-t border-[#f2f2f2] pt-10 md:pt-20 mt-20 flex max-md:flex-col gap-y-10 items-start justify-between w-full'>
                  <div className='max-w-[364px] w-full flex flex-col'>
                    <h3 className='mt-4 text-heading font-bold text-[32px]'>
                      Each Year, One Year-End Financial Package
                    </h3>
                    <p className='mt-2 text-body'>
                      Get a year-end financial package for each year of
                      retroactive accounting with our customised retroactive
                      accounting and flexible payment plan.
                    </p>
                  </div>
                  <div className='flex flex-col max-w-[530px] w-full gap-y-5'>
                    <Check
                      title='No-frills pricing'
                      details='Like with our other bundles, enjoy stable pricing with Retroactive Bookkeeping with no additional charges, hourly rates, up charges, or hidden fees. Our fixed price structure motivates us to complete the work as fast as possible and our reputation, efficiently.'
                    />
                    <Check
                      title='All your reports in one place'
                      details='Say goodbye to scattered financial documents - our Year End Financial Package includes your IFRS compliant income statement, balance sheet, statement of cash flows, and notes to the accounts, all in one place.'
                    />

                    <Check
                      title='Organised and Efficient'
                      details='Our Year End Financial Package is designed to make catching up on years of financial records as efficient and organised as possible making it easy for you to understand your financial situation.'
                    />
                  </div>
                </div>
              </Group>
            </Group>
          </div>
        </div>
      </Group>
      <SupportCard />
      <Testimonials />
    </div>
  );
}
